#!/usr/bin/env python3
"""Build the offline version of the swipe app for GitHub Pages.

GitHub Pages serves files, not processes, so there is no Python and no way to
write to the repository. The build therefore bakes the card payload into
`state.json` and marks the bundle static. The page then stages decisions in the
browser and hands a patch back through GitHub, which
[scripts/swipe.py](../scripts/swipe.py) applies. `db.json` stays the only
record: the browser holds a staging area, never a second source of truth.

    python3 app/build_static.py                     # writes ./site
    python3 app/build_static.py --out /tmp/site --repo owner/name

The repository is needed for the save link and otherwise comes from
`GITHUB_REPOSITORY`. Without it the bundle still builds and still swipes, but
the page can only copy a patch to the clipboard.
"""

import argparse
import json
import os
import shutil
import sys
from pathlib import Path

APP_DIR = Path(__file__).resolve().parent
REPO = APP_DIR.parent
sys.path.insert(0, str(REPO / "scripts"))
sys.path.insert(0, str(APP_DIR))

import server  # noqa: E402
import state  # noqa: E402
import swipe  # noqa: E402

STATIC_DIR = APP_DIR / "static"
COPIED = ("index.html", "app.css", "app.js", "days.js", "snapshot.js")
INBOX = "inbox/decisions.txt"


def snapshot(db):
    """One flat, chronological card list. The page derives the deck and the
    three groups from it, so a locally staged decision only moves a card.

    Ordered by the same parsed key as the swipe deck, not by the display strings,
    so events either side of a daylight-saving change keep their real order.
    """
    events = {}
    for event in swipe.deck(db):
        events[event["event_id"]] = event
    for rows in swipe.decided(db).values():
        for event in rows:
            events.setdefault(event["event_id"], event)
    cards = [server.card(event) for event in sorted(events.values(), key=swipe.sort_key)]
    base = server.payload(db)
    return {"clock": base["clock"], "labels": base["labels"], "cards": cards}


def mode_script(repo, branch, inbox):
    owner, _, name = (repo or "").partition("/")
    target = {"owner": owner, "repo": name, "branch": branch, "inbox": inbox}
    return ("/* Generated by app/build_static.py. Do not edit. */\n"
            "window.SWIPE_MODE = 'static';\n"
            f"window.SWIPE_REPO = {json.dumps(target, ensure_ascii=False)};\n")


def build(db_path, out_dir, repo=None, branch="main", inbox=INBOX):
    db = state.load(db_path)  # refuses to build a bundle from missing state
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    for name in COPIED:
        shutil.copyfile(STATIC_DIR / name, out / name)
    generated = {
        "mode.js": mode_script(repo, branch, inbox),
        "state.json": state.json_text(snapshot(db)),
        # Pages would otherwise hand the bundle to Jekyll, which skips _ paths.
        ".nojekyll": "",
    }
    for name, content in generated.items():
        state.atomic_write(out / name, content)
        os.chmod(out / name, 0o644)  # atomic_write keeps a private temp mode
    return out


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--db", default=str(REPO / "db.json"))
    parser.add_argument("--out", default=str(REPO / "site"))
    parser.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY", ""),
                        help="owner/name for the save link")
    parser.add_argument("--branch", default="main")
    parser.add_argument("--inbox", default=INBOX)
    args = parser.parse_args()
    try:
        out = build(args.db, args.out, args.repo, args.branch, args.inbox)
    except (OSError, ValueError) as error:
        parser.exit(1, f"Error: {error}\n")
    snap = json.loads((out / "state.json").read_text(encoding="utf-8"))
    print(f"Built {out} with {len(snap['cards'])} card(s)")
    if not args.repo:
        print("No --repo and no GITHUB_REPOSITORY: the save link is disabled.")


if __name__ == "__main__":
    main()
